#!/bin/bash
clear

yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
nama=$(cat /etc/xray/username)

# . Liner 
function baris_panjang() {
  echo -e " ◇━━━━━━━━━━━━━━━━━◇ "
}

function Newbie_Banner() {
clear
baris_panjang
echo -e "           $nama       "
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "  Terimakasih Telah Menggunakan "
echo -e "          Script Credit "
echo -e "          $nama "
baris_panjang
exit 1
}

duration=3
frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")

# Menghitung jumlah frame
num_frames=${#frames[@]}

# Menghitung jumlah iterasi
num_iterations=$((duration))

# Fungsi untuk menampilkan animasi loading berwarna

Loading_Animasi() {
    for ((i = 0; i < num_iterations; i++)); do
        clear
        index=$((i % num_frames))
        color_code=$((31 + i % 7))
echo ""
echo ""
echo ""
echo -e "\e[1;${color_code}m ${frames[$index]}\e[0m"
sleep 0.5
    done
}

# Menjalankan animasi loading

# Menampilkan pesan setelah animasi selesai
function Loading_Succes() {
clear
echo -e  "\033[5;32mSucces\033[0m"
sleep 2
clear
}


function Daftar_Member_Vmess() {
    echo ""
  	grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
    echo ""

}

function Daftar_Member_Vless() {
    echo ""
  	grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
    echo ""
}

function Daftar_Member_Trojan() {
    echo ""
	grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
    echo ""
}

Newbie_Banner
baris_panjang
echo -e "           ACCOUNT VMESS   "
baris_panjang
Daftar_Member_Vmess
baris_panjang
echo "     "
baris_panjang
echo -e "           ACCOUNT VLESS   "
baris_panjang
Daftar_Member_Vless
baris_panjang
echo "     "
baris_panjang
echo -e "           ACCOUNT TROJAN   "
baris_panjang
Daftar_Member_Trojan
baris_panjang
Sc_Credit
